# Generated by Django 4.2.7 on 2023-12-02 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videostreamingapp', '0003_video_category_video_description_video_director_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='duration',
        ),
    ]
