# Generated by Django 4.2.7 on 2023-12-02 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videostreamingapp', '0004_remove_video_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='description',
        ),
        migrations.RemoveField(
            model_name='video',
            name='director',
        ),
        migrations.RemoveField(
            model_name='video',
            name='release_date',
        ),
    ]
